### ISSUE TITLE
Examine poor quality data for 2022-01-04

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#145]
There are some bad data for 2022-01-04.

- Can the data be fixed?
- Can the data be marked bad?

**Comment by mgalloy** [comment]
The data that passes GBU is actually bad.

**Comment by detoma** [comment]
Agreed. A threshold of 30 for BKG is high. We need to plot the median BKG again as a function of time and reassess it.

We knew a V cross-talk of 4 was passing bad data. A 2-2.5 threshold would be better. We did that because we were removing too many data. Hopefully we can align raw data and improve polarization.

**Comment by mgalloy** [comment]
I made a list of all the files with background > 20.0 (and 25.0), and some are not great looking, but a lot of them are still recognizable as coronal, as opposed to the data on this day.

**Comment by mgalloy** [comment]
The implementation of the median difference GBU check is catching some more files now.

For the two (bad) 637 nm files, it catches them both:

    Filename                               Reason     Bkg         V      RCAM      TCAM   Sigma
    20220104.191847.ucomp.637.l1.3.fts         64    15.8      0.87       0.2       0.3    2.00
    20220104.192624.ucomp.637.l1.3.fts         64    15.7      0.89       0.2       0.3    2.00
