### ISSUE TITLE
Define level 2 data products for commissioning

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#195]
(If this is captured in another issue and I am not seeing it, please close this one).

During the workshop, the team talked about the potential for combining the polarization and dynamics data products into a single file. This would be a significant change to our external interfaces, breaking the forward interaction with UCOMP and making our limited documentation obsolete. But if it is worth doing, it is worth doing now because it affects external interfaces, documentation, masks, etc.  

I would propose that all quality L1 files and the mean and median files get 1 L2 fits file that looks like this:

- "Center wavelength intensity" [All wavelengths]  comment: "intensity at center tuning wavelength"
- "Enhanced intensity" [All wavelengths] comment: "unsharp mask of center wavelength intensity"
- "Peak Intensity" [All wavelengths] comment: "peak of Gaussian fit"  
- "LOS Velocity" [All wavelengths] comment: "Doppler velocity from Gaussian fit"
- "Line Width" [All wavelengths] comment: "FWHM from Gaussian fit"
- "Weighted average I" [1074/1079 only] comment: "sum of I at center 3 wavelengths / 2"
- "Weighted average Q" (Q/I in the quick look) [1074/1079 only] comment: "sum of Q at center 3 wavelengths / 2"
- "Weighted average U" (U/I in the quick look) [1074/1079 only] comment: "sum of U at center 3 wavelengths / 2"
- "Weighted average L" (Log L/I in the quick look) [1074/1079 only] comment: "sum of L at center 3 wavelengths / 2"
- "Azimuth" [1074/1079 only]  comment: "0.5 * atan(weighted U / weighted Q)"
- "Radial Azimuth" [1074/1079 only] comment: "azimuth with respect to radial direction"

Mean and Median also get a second IQUV.all (L1) like FITS file.

Questions to answer on this:

- Do you think this change is needed?  We will be shipping a lot of 637 polarization fits extensions with lots of noise and no signal.
- Are these the correct extensions?
- Are they the correct names?
- Does every product get quicklooks?
- Does every product get fits extensions?
- This mixes dynamics and polarization processing in one file; is there a good way to denote the different processing schemes we use between the dynamics and polarization products (gaussian vs. summing)?  
- Could/should we put an empty fits extension that says Gaussian processing and another one that says summed processing to give visual clues for folks exploring the files with ds9,fv, etc.?  Or would this just be more confusing and break code that expects data in every extension.
- Should we lean on extension names to differentiate changing LOS Velocity to Gaussian Fit LOS Velocity
- Should we put notes in the header? For U, this processing was done by summing across the 3 points closest to the line center.  For LOS Velocity (in 3-point data): This processing was done with a 3-point analytical gauss.  For LOS Velocity (in 5-point data): this processing was done with a gaussian fit to the data.  ETC

**Comment by detoma** [comment]
I think this change is needed given the confusion that the current system is causing.

We will have extra polarization extensions for 1074 and 1079 (Q, U, L, Azimuth). We do not need them for the other lines. 

The data products will be described in details in the data user guide and in a succinct way in the extension header.

We have three flavors of Intensity: the intensity that correspond to the nominal line center, e.g. 1074.74, the peak intensity from the gaussian fit, and the summed intensity. They should all be reported in the level 2 fits, in my opinion. 

If we have only one level 2 fits file, we do not need multiple flavors of enhanced intensity. This resolves the issue to make an enhanced intensity for the peak gaussian intensity which was problematic. We can simply compute the enhanced intensity for the line center or for the summed intensity.

Since we are switching to FWHM, we should spell it out to make it clear.

**Comment by bberkeyU** [comment]
@detoma  How do we compute the 3rd intensity measurement? I understand how we get the summed and Gaussian fit intensity.  But is the 3rd one just the L1 center wavelength intensity with no extra processing?

What do we call these 3?
Summed
Peak
Nominal?

**Comment by bberkeyU** [comment]
May need headers to explain the flavors of intensity since we will have 3.

**Comment by mgalloy** [comment]
Need to give Sarah G. a heads-up that this will require changes to Forward.
